### ISSUE TITLE
No way for 'chosen' name to go through to HomeKit?

### ISSUE THREAD

**Issue by jmlumpkin** [asednev/homebridge-plugin-govee#52] opened 2022-01-02 21:34 UTC
**Describe Your Problem:**

Each of my sensors have a name (Garage, Office, Small/Large Bin). Each of those I have set up in the UI to have that name, but when looking at HomeKit (and the 'Name' section in the accessory) It is the GVH5101XXXX. I was wondering if instead of those names going to HomeKit, the 'chosen' name given in the UI could instead (if set). 

**Logs:**

```
[1/2/2022, 9:09:27 PM] [Govee] Restoring existing accessory from cache: GVH51011234
[1/2/2022, 9:09:27 PM] [Govee] Restoring existing accessory from cache: GVH51015555
[1/2/2022, 9:09:28 PM] [Govee] Restoring existing accessory from cache: GVH51016633
```

**Plugin Config:**

```json
{
"name": "Govee",
"batteryThreshold": 25,
"debug": false,
"humidityOffset": 0,
"platform": "GoveeHomebridgePlugin"
}
```

**Screenshots:**
None

**Environment:**

* **Plugin Version**: 1.1.4
* **Homebridge Version**: 1.3.9
* **Node.js Version**: 14.18.2
* **NPM Version**:  6.14.15
* **Operating System**:  Ubuntu

**Comment by asednev** [comment] 2022-01-28 19:06
This is a duplicate of https://github.com/asednev/homebridge-plugin-govee/issues/30. At this time, I don't see a way to get the device name from data broadcasted over BLE. Most likely Govee maintains device name in the iOS app.

**Closed by asednev** 2022-01-28 19:06 UTC
Labels: question

**Comment by jmlumpkin** [comment] 2022-01-28 19:15
One question beyond that - HomeBridge let's you name the accessories- could that not be read and sent back to HomeKit?
